//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IFileClient {

    getLogFileInfos(projectName: string | null | undefined): Promise<LogFileInfo[]>;

    importAll(projectName: string | null | undefined): Promise<{ [key: string]: LogFileInfo; }>;

    importLog(projectName: string | null | undefined, fileName: string | null | undefined): Promise<LogFileInfo | null>;

    exportOcel(projectName: string | null | undefined, format: string | null | undefined): Promise<FileResponse | null>;
}

export class FileClient implements IFileClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getLogFileInfos(projectName: string | null | undefined): Promise<LogFileInfo[]> {
        let url_ = this.baseUrl + "/api/File/logFileInfos?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLogFileInfos(_response);
        });
    }

    protected processGetLogFileInfos(response: Response): Promise<LogFileInfo[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(LogFileInfo.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LogFileInfo[]>(null as any);
    }

    importAll(projectName: string | null | undefined): Promise<{ [key: string]: LogFileInfo; }> {
        let url_ = this.baseUrl + "/api/File/importAll?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processImportAll(_response);
        });
    }

    protected processImportAll(response: Response): Promise<{ [key: string]: LogFileInfo; }> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200) {
                result200 = {} as any;
                for (let key in resultData200) {
                    if (resultData200.hasOwnProperty(key))
                        (<any>result200)![key] = resultData200[key] ? LogFileInfo.fromJS(resultData200[key]) : new LogFileInfo();
                }
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<{ [key: string]: LogFileInfo; }>(null as any);
    }

    importLog(projectName: string | null | undefined, fileName: string | null | undefined): Promise<LogFileInfo | null> {
        let url_ = this.baseUrl + "/api/File/importLog?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        if (fileName !== undefined && fileName !== null)
            url_ += "fileName=" + encodeURIComponent("" + fileName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processImportLog(_response);
        });
    }

    protected processImportLog(response: Response): Promise<LogFileInfo | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? LogFileInfo.fromJS(resultData200) : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LogFileInfo | null>(null as any);
    }

    exportOcel(projectName: string | null | undefined, format: string | null | undefined): Promise<FileResponse | null> {
        let url_ = this.baseUrl + "/api/File/exportOcel?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        if (format !== undefined && format !== null)
            url_ += "format=" + encodeURIComponent("" + format) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExportOcel(_response);
        });
    }

    protected processExportOcel(response: Response): Promise<FileResponse | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse | null>(null as any);
    }
}

export interface IMapClient {

    getLogInfo(projectName: string | null | undefined): Promise<LogInfo>;

    discoverOcDfg(projectName: string | null | undefined, options: OcDfgOptions): Promise<DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo>;

    getAllNodesInLog(projectName: string | null | undefined): Promise<LogNode[]>;

    saveNodeCalculations(projectName: string | null | undefined, calculations: NodeCalculation[]): Promise<void>;

    computeLayoutWithModel(projectName: string | null | undefined, modelAndOptions: ValueTupleOfDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfoAndGraphLayoutOptions): Promise<GraphLayout>;

    computeLayout(projectName: string | null | undefined, options: OcDfgLayoutOptions): Promise<GraphLayout>;

    discoverOcDfgAndGenerateDot(projectName: string | null | undefined, groupByNamespace: boolean | undefined, options: OcDfgOptions): Promise<string>;

    /**
     * @param projectName (optional) 
     * @deprecated
     */
    getNamespaceTree(projectName: string | null | undefined): Promise<ListTreeOfString>;
}

export class MapClient implements IMapClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getLogInfo(projectName: string | null | undefined): Promise<LogInfo> {
        let url_ = this.baseUrl + "/api/Map/getLogInfo?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLogInfo(_response);
        });
    }

    protected processGetLogInfo(response: Response): Promise<LogInfo> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = LogInfo.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LogInfo>(null as any);
    }

    discoverOcDfg(projectName: string | null | undefined, options: OcDfgOptions): Promise<DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo> {
        let url_ = this.baseUrl + "/api/Map/discoverOcDfg?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(options);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDiscoverOcDfg(_response);
        });
    }

    protected processDiscoverOcDfg(response: Response): Promise<DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo>(null as any);
    }

    getAllNodesInLog(projectName: string | null | undefined): Promise<LogNode[]> {
        let url_ = this.baseUrl + "/api/Map/getAllNodesInLog?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllNodesInLog(_response);
        });
    }

    protected processGetAllNodesInLog(response: Response): Promise<LogNode[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(LogNode.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LogNode[]>(null as any);
    }

    saveNodeCalculations(projectName: string | null | undefined, calculations: NodeCalculation[]): Promise<void> {
        let url_ = this.baseUrl + "/api/Map/saveNodeCalculations?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(calculations);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveNodeCalculations(_response);
        });
    }

    protected processSaveNodeCalculations(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    computeLayoutWithModel(projectName: string | null | undefined, modelAndOptions: ValueTupleOfDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfoAndGraphLayoutOptions): Promise<GraphLayout> {
        let url_ = this.baseUrl + "/api/Map/computeLayoutWithModel?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(modelAndOptions);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processComputeLayoutWithModel(_response);
        });
    }

    protected processComputeLayoutWithModel(response: Response): Promise<GraphLayout> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GraphLayout.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GraphLayout>(null as any);
    }

    computeLayout(projectName: string | null | undefined, options: OcDfgLayoutOptions): Promise<GraphLayout> {
        let url_ = this.baseUrl + "/api/Map/computeLayout?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(options);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processComputeLayout(_response);
        });
    }

    protected processComputeLayout(response: Response): Promise<GraphLayout> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GraphLayout.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GraphLayout>(null as any);
    }

    discoverOcDfgAndGenerateDot(projectName: string | null | undefined, groupByNamespace: boolean | undefined, options: OcDfgOptions): Promise<string> {
        let url_ = this.baseUrl + "/api/Map/discoverOcDfgAndDot?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        if (groupByNamespace === null)
            throw new Error("The parameter 'groupByNamespace' cannot be null.");
        else if (groupByNamespace !== undefined)
            url_ += "groupByNamespace=" + encodeURIComponent("" + groupByNamespace) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(options);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDiscoverOcDfgAndGenerateDot(_response);
        });
    }

    protected processDiscoverOcDfgAndGenerateDot(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @param projectName (optional) 
     * @deprecated
     */
    getNamespaceTree(projectName: string | null | undefined): Promise<ListTreeOfString> {
        let url_ = this.baseUrl + "/api/Map/namespaceTree?";
        if (projectName !== undefined && projectName !== null)
            url_ += "projectName=" + encodeURIComponent("" + projectName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetNamespaceTree(_response);
        });
    }

    protected processGetNamespaceTree(response: Response): Promise<ListTreeOfString> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ListTreeOfString.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ListTreeOfString>(null as any);
    }
}

export interface IProjectClient {

    create(name: string | null | undefined, logDir: string | null | undefined): Promise<void>;

    delete(name: string | null | undefined): Promise<void>;
}

export class ProjectClient implements IProjectClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    create(name: string | null | undefined, logDir: string | null | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Project/create?";
        if (name !== undefined && name !== null)
            url_ += "name=" + encodeURIComponent("" + name) + "&";
        if (logDir !== undefined && logDir !== null)
            url_ += "logDir=" + encodeURIComponent("" + logDir) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    delete(name: string | null | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Project/delete?";
        if (name !== undefined && name !== null)
            url_ += "name=" + encodeURIComponent("" + name) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class LogFileInfo implements ILogFileInfo {
    id!: string;
    noOfImportedEvents!: number;
    noOfImportedObjects!: number;
    fileSize!: number;
    lastImported?: Date | undefined;
    lastChanged?: Date | undefined;

    constructor(data?: ILogFileInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.noOfImportedEvents = _data["noOfImportedEvents"];
            this.noOfImportedObjects = _data["noOfImportedObjects"];
            this.fileSize = _data["fileSize"];
            this.lastImported = _data["lastImported"] ? new Date(_data["lastImported"].toString()) : <any>undefined;
            this.lastChanged = _data["lastChanged"] ? new Date(_data["lastChanged"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): LogFileInfo {
        data = typeof data === 'object' ? data : {};
        let result = new LogFileInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["noOfImportedEvents"] = this.noOfImportedEvents;
        data["noOfImportedObjects"] = this.noOfImportedObjects;
        data["fileSize"] = this.fileSize;
        data["lastImported"] = this.lastImported ? this.lastImported.toISOString() : <any>undefined;
        data["lastChanged"] = this.lastChanged ? this.lastChanged.toISOString() : <any>undefined;
        return data;
    }
}

export interface ILogFileInfo {
    id: string;
    noOfImportedEvents: number;
    noOfImportedObjects: number;
    fileSize: number;
    lastImported?: Date | undefined;
    lastChanged?: Date | undefined;
}

export class LogInfo implements ILogInfo {
    objectTypes!: string[];

    constructor(data?: ILogInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.objectTypes = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["objectTypes"])) {
                this.objectTypes = [] as any;
                for (let item of _data["objectTypes"])
                    this.objectTypes!.push(item);
            }
        }
    }

    static fromJS(data: any): LogInfo {
        data = typeof data === 'object' ? data : {};
        let result = new LogInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.objectTypes)) {
            data["objectTypes"] = [];
            for (let item of this.objectTypes)
                data["objectTypes"].push(item);
        }
        return data;
    }
}

export interface ILogInfo {
    objectTypes: string[];
}

export class DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo implements IDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo {
    nodes?: NodeOfNodeInfo[] | undefined;
    edges?: TupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo[] | undefined;

    constructor(data?: IDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["nodes"])) {
                this.nodes = [] as any;
                for (let item of _data["nodes"])
                    this.nodes!.push(NodeOfNodeInfo.fromJS(item));
            }
            if (Array.isArray(_data["edges"])) {
                this.edges = [] as any;
                for (let item of _data["edges"])
                    this.edges!.push(TupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo.fromJS(item));
            }
        }
    }

    static fromJS(data: any): DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo {
        data = typeof data === 'object' ? data : {};
        let result = new DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.nodes)) {
            data["nodes"] = [];
            for (let item of this.nodes)
                data["nodes"].push(item.toJSON());
        }
        if (Array.isArray(this.edges)) {
            data["edges"] = [];
            for (let item of this.edges)
                data["edges"].push(item.toJSON());
        }
        return data;
    }
}

export interface IDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo {
    nodes?: NodeOfNodeInfo[] | undefined;
    edges?: TupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo[] | undefined;
}

export abstract class NodeOfNodeInfo implements INodeOfNodeInfo {

    constructor(data?: INodeOfNodeInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): NodeOfNodeInfo {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'NodeOfNodeInfo' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface INodeOfNodeInfo {
}

export class TupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo implements ITupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo {
    item1!: NodeOfNodeInfo;
    item2!: NodeOfNodeInfo;
    item3!: EdgeOfEdgeInfo;

    constructor(data?: ITupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.item3 = new EdgeOfEdgeInfo();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.item1 = _data["item1"] ? NodeOfNodeInfo.fromJS(_data["item1"]) : <any>undefined;
            this.item2 = _data["item2"] ? NodeOfNodeInfo.fromJS(_data["item2"]) : <any>undefined;
            this.item3 = _data["item3"] ? EdgeOfEdgeInfo.fromJS(_data["item3"]) : new EdgeOfEdgeInfo();
        }
    }

    static fromJS(data: any): TupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo {
        data = typeof data === 'object' ? data : {};
        let result = new TupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["item1"] = this.item1 ? this.item1.toJSON() : <any>undefined;
        data["item2"] = this.item2 ? this.item2.toJSON() : <any>undefined;
        data["item3"] = this.item3 ? this.item3.toJSON() : <any>undefined;
        return data;
    }
}

export interface ITupleOfNodeOfNodeInfoAndNodeOfNodeInfoAndEdgeOfEdgeInfo {
    item1: NodeOfNodeInfo;
    item2: NodeOfNodeInfo;
    item3: EdgeOfEdgeInfo;
}

export class EdgeOfEdgeInfo implements IEdgeOfEdgeInfo {
    weight!: number;
    type?: FSharpOptionOfString | undefined;
    info?: FSharpOptionOfEdgeInfo | undefined;

    constructor(data?: IEdgeOfEdgeInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.weight = _data["weight"];
            this.type = _data["type"] ? FSharpOptionOfString.fromJS(_data["type"]) : <any>undefined;
            this.info = _data["info"] ? FSharpOptionOfEdgeInfo.fromJS(_data["info"]) : <any>undefined;
        }
    }

    static fromJS(data: any): EdgeOfEdgeInfo {
        data = typeof data === 'object' ? data : {};
        let result = new EdgeOfEdgeInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["weight"] = this.weight;
        data["type"] = this.type ? this.type.toJSON() : <any>undefined;
        data["info"] = this.info ? this.info.toJSON() : <any>undefined;
        return data;
    }
}

export interface IEdgeOfEdgeInfo {
    weight: number;
    type?: FSharpOptionOfString | undefined;
    info?: FSharpOptionOfEdgeInfo | undefined;
}

export class FSharpOptionOfString implements IFSharpOptionOfString {

    constructor(data?: IFSharpOptionOfString) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): FSharpOptionOfString {
        data = typeof data === 'object' ? data : {};
        let result = new FSharpOptionOfString();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IFSharpOptionOfString {
}

export class FSharpOptionOfEdgeInfo implements IFSharpOptionOfEdgeInfo {

    constructor(data?: IFSharpOptionOfEdgeInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): FSharpOptionOfEdgeInfo {
        data = typeof data === 'object' ? data : {};
        let result = new FSharpOptionOfEdgeInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IFSharpOptionOfEdgeInfo {
}

export class OcDfgOptions implements IOcDfgOptions {
    minimumEvents!: number;
    minimumOccurrence!: number;
    minimumSuccessions!: number;
    includedTypes!: string[];

    constructor(data?: IOcDfgOptions) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.includedTypes = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.minimumEvents = _data["minimumEvents"];
            this.minimumOccurrence = _data["minimumOccurrence"];
            this.minimumSuccessions = _data["minimumSuccessions"];
            if (Array.isArray(_data["includedTypes"])) {
                this.includedTypes = [] as any;
                for (let item of _data["includedTypes"])
                    this.includedTypes!.push(item);
            }
        }
    }

    static fromJS(data: any): OcDfgOptions {
        data = typeof data === 'object' ? data : {};
        let result = new OcDfgOptions();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["minimumEvents"] = this.minimumEvents;
        data["minimumOccurrence"] = this.minimumOccurrence;
        data["minimumSuccessions"] = this.minimumSuccessions;
        if (Array.isArray(this.includedTypes)) {
            data["includedTypes"] = [];
            for (let item of this.includedTypes)
                data["includedTypes"].push(item);
        }
        return data;
    }
}

export interface IOcDfgOptions {
    minimumEvents: number;
    minimumOccurrence: number;
    minimumSuccessions: number;
    includedTypes: string[];
}

export class LogNode implements ILogNode {
    id!: string;
    displayName!: string;
    nodeType!: NodeType;

    constructor(data?: ILogNode) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.displayName = _data["displayName"];
            this.nodeType = _data["nodeType"] ? NodeType.fromJS(_data["nodeType"]) : <any>undefined;
        }
    }

    static fromJS(data: any): LogNode {
        data = typeof data === 'object' ? data : {};
        let result = new LogNode();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["displayName"] = this.displayName;
        data["nodeType"] = this.nodeType ? this.nodeType.toJSON() : <any>undefined;
        return data;
    }
}

export interface ILogNode {
    id: string;
    displayName: string;
    nodeType: NodeType;
}

export abstract class NodeType implements INodeType {

    protected _discriminator: string;

    constructor(data?: INodeType) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        this._discriminator = "NodeType";
    }

    init(_data?: any) {
    }

    static fromJS(data: any): NodeType {
        data = typeof data === 'object' ? data : {};
        if (data["discriminator"] === "Event") {
            let result = new Event();
            result.init(data);
            return result;
        }
        if (data["discriminator"] === "Start") {
            let result = new Start();
            result.init(data);
            return result;
        }
        if (data["discriminator"] === "End") {
            let result = new End();
            result.init(data);
            return result;
        }
        throw new Error("The abstract class 'NodeType' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["discriminator"] = this._discriminator;
        return data;
    }
}

export interface INodeType {
}

export class Event extends NodeType implements IEvent {

    constructor(data?: IEvent) {
        super(data);
        this._discriminator = "Event";
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): Event {
        data = typeof data === 'object' ? data : {};
        let result = new Event();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IEvent extends INodeType {
}

export class Start extends NodeType implements IStart {
    objectType!: string;

    constructor(data?: IStart) {
        super(data);
        this._discriminator = "Start";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.objectType = _data["objectType"];
        }
    }

    static override fromJS(data: any): Start {
        data = typeof data === 'object' ? data : {};
        let result = new Start();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["objectType"] = this.objectType;
        super.toJSON(data);
        return data;
    }
}

export interface IStart extends INodeType {
    objectType: string;
}

export class End extends NodeType implements IEnd {
    objectType!: string;

    constructor(data?: IEnd) {
        super(data);
        this._discriminator = "End";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.objectType = _data["objectType"];
        }
    }

    static override fromJS(data: any): End {
        data = typeof data === 'object' ? data : {};
        let result = new End();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["objectType"] = this.objectType;
        super.toJSON(data);
        return data;
    }
}

export interface IEnd extends INodeType {
    objectType: string;
}

export class NodeCalculation implements INodeCalculation {
    nodeId!: string;
    textWrap!: string[];
    size!: Size;
    nodeType!: NodeType;

    constructor(data?: INodeCalculation) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.textWrap = [];
            this.size = new Size();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.nodeId = _data["nodeId"];
            if (Array.isArray(_data["textWrap"])) {
                this.textWrap = [] as any;
                for (let item of _data["textWrap"])
                    this.textWrap!.push(item);
            }
            this.size = _data["size"] ? Size.fromJS(_data["size"]) : new Size();
            this.nodeType = _data["nodeType"] ? NodeType.fromJS(_data["nodeType"]) : <any>undefined;
        }
    }

    static fromJS(data: any): NodeCalculation {
        data = typeof data === 'object' ? data : {};
        let result = new NodeCalculation();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["nodeId"] = this.nodeId;
        if (Array.isArray(this.textWrap)) {
            data["textWrap"] = [];
            for (let item of this.textWrap)
                data["textWrap"].push(item);
        }
        data["size"] = this.size ? this.size.toJSON() : <any>undefined;
        data["nodeType"] = this.nodeType ? this.nodeType.toJSON() : <any>undefined;
        return data;
    }
}

export interface INodeCalculation {
    nodeId: string;
    textWrap: string[];
    size: Size;
    nodeType: NodeType;
}

export class Size implements ISize {
    width!: number;
    height!: number;

    constructor(data?: ISize) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.width = _data["width"];
            this.height = _data["height"];
        }
    }

    static fromJS(data: any): Size {
        data = typeof data === 'object' ? data : {};
        let result = new Size();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["width"] = this.width;
        data["height"] = this.height;
        return data;
    }
}

export interface ISize {
    width: number;
    height: number;
}

export class GraphLayout implements IGraphLayout {
    nodes!: Node[];
    edges!: Edge[];

    constructor(data?: IGraphLayout) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.nodes = [];
            this.edges = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["nodes"])) {
                this.nodes = [] as any;
                for (let item of _data["nodes"])
                    this.nodes!.push(Node.fromJS(item));
            }
            if (Array.isArray(_data["edges"])) {
                this.edges = [] as any;
                for (let item of _data["edges"])
                    this.edges!.push(Edge.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GraphLayout {
        data = typeof data === 'object' ? data : {};
        let result = new GraphLayout();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.nodes)) {
            data["nodes"] = [];
            for (let item of this.nodes)
                data["nodes"].push(item.toJSON());
        }
        if (Array.isArray(this.edges)) {
            data["edges"] = [];
            for (let item of this.edges)
                data["edges"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGraphLayout {
    nodes: Node[];
    edges: Edge[];
}

export class Node implements INode {
    id!: string;
    text!: string[];
    nodeType!: NodeType;
    position!: Coordinate;
    size!: Size;
    rank!: number;
    nodeInfo?: NodeInfo | undefined;

    constructor(data?: INode) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.text = [];
            this.position = new Coordinate();
            this.size = new Size();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            if (Array.isArray(_data["text"])) {
                this.text = [] as any;
                for (let item of _data["text"])
                    this.text!.push(item);
            }
            this.nodeType = _data["nodeType"] ? NodeType.fromJS(_data["nodeType"]) : <any>undefined;
            this.position = _data["position"] ? Coordinate.fromJS(_data["position"]) : new Coordinate();
            this.size = _data["size"] ? Size.fromJS(_data["size"]) : new Size();
            this.rank = _data["rank"];
            this.nodeInfo = _data["nodeInfo"] ? NodeInfo.fromJS(_data["nodeInfo"]) : <any>undefined;
        }
    }

    static fromJS(data: any): Node {
        data = typeof data === 'object' ? data : {};
        let result = new Node();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        if (Array.isArray(this.text)) {
            data["text"] = [];
            for (let item of this.text)
                data["text"].push(item);
        }
        data["nodeType"] = this.nodeType ? this.nodeType.toJSON() : <any>undefined;
        data["position"] = this.position ? this.position.toJSON() : <any>undefined;
        data["size"] = this.size ? this.size.toJSON() : <any>undefined;
        data["rank"] = this.rank;
        data["nodeInfo"] = this.nodeInfo ? this.nodeInfo.toJSON() : <any>undefined;
        return data;
    }
}

export interface INode {
    id: string;
    text: string[];
    nodeType: NodeType;
    position: Coordinate;
    size: Size;
    rank: number;
    nodeInfo?: NodeInfo | undefined;
}

export class Coordinate implements ICoordinate {
    x!: number;
    y!: number;

    constructor(data?: ICoordinate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.x = _data["x"];
            this.y = _data["y"];
        }
    }

    static fromJS(data: any): Coordinate {
        data = typeof data === 'object' ? data : {};
        let result = new Coordinate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["x"] = this.x;
        data["y"] = this.y;
        return data;
    }
}

export interface ICoordinate {
    x: number;
    y: number;
}

export class NodeInfo implements INodeInfo {
    frequency!: number;
    namespace?: FSharpOptionOfString | undefined;
    level?: FSharpOptionOfLogLevel | undefined;

    constructor(data?: INodeInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.frequency = _data["frequency"];
            this.namespace = _data["namespace"] ? FSharpOptionOfString.fromJS(_data["namespace"]) : <any>undefined;
            this.level = _data["level"] ? FSharpOptionOfLogLevel.fromJS(_data["level"]) : <any>undefined;
        }
    }

    static fromJS(data: any): NodeInfo {
        data = typeof data === 'object' ? data : {};
        let result = new NodeInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["frequency"] = this.frequency;
        data["namespace"] = this.namespace ? this.namespace.toJSON() : <any>undefined;
        data["level"] = this.level ? this.level.toJSON() : <any>undefined;
        return data;
    }
}

export interface INodeInfo {
    frequency: number;
    namespace?: FSharpOptionOfString | undefined;
    level?: FSharpOptionOfLogLevel | undefined;
}

export class FSharpOptionOfLogLevel implements IFSharpOptionOfLogLevel {

    constructor(data?: IFSharpOptionOfLogLevel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): FSharpOptionOfLogLevel {
        data = typeof data === 'object' ? data : {};
        let result = new FSharpOptionOfLogLevel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IFSharpOptionOfLogLevel {
}

export class Edge implements IEdge {
    sourceId!: string;
    targetId!: string;
    waypoints!: Coordinate[];
    downwards!: boolean;
    totalWeight!: number;
    typeInfos!: EdgeTypeInfoOfEdgeInfo[];

    constructor(data?: IEdge) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.waypoints = [];
            this.typeInfos = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.sourceId = _data["sourceId"];
            this.targetId = _data["targetId"];
            if (Array.isArray(_data["waypoints"])) {
                this.waypoints = [] as any;
                for (let item of _data["waypoints"])
                    this.waypoints!.push(Coordinate.fromJS(item));
            }
            this.downwards = _data["downwards"];
            this.totalWeight = _data["totalWeight"];
            if (Array.isArray(_data["typeInfos"])) {
                this.typeInfos = [] as any;
                for (let item of _data["typeInfos"])
                    this.typeInfos!.push(EdgeTypeInfoOfEdgeInfo.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Edge {
        data = typeof data === 'object' ? data : {};
        let result = new Edge();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["sourceId"] = this.sourceId;
        data["targetId"] = this.targetId;
        if (Array.isArray(this.waypoints)) {
            data["waypoints"] = [];
            for (let item of this.waypoints)
                data["waypoints"].push(item.toJSON());
        }
        data["downwards"] = this.downwards;
        data["totalWeight"] = this.totalWeight;
        if (Array.isArray(this.typeInfos)) {
            data["typeInfos"] = [];
            for (let item of this.typeInfos)
                data["typeInfos"].push(item.toJSON());
        }
        return data;
    }
}

export interface IEdge {
    sourceId: string;
    targetId: string;
    waypoints: Coordinate[];
    downwards: boolean;
    totalWeight: number;
    typeInfos: EdgeTypeInfoOfEdgeInfo[];
}

export class EdgeTypeInfoOfEdgeInfo implements IEdgeTypeInfoOfEdgeInfo {
    weight!: number;
    type?: string | undefined;
    info?: EdgeInfo | undefined;

    constructor(data?: IEdgeTypeInfoOfEdgeInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.weight = _data["weight"];
            this.type = _data["type"];
            this.info = _data["info"] ? EdgeInfo.fromJS(_data["info"]) : <any>undefined;
        }
    }

    static fromJS(data: any): EdgeTypeInfoOfEdgeInfo {
        data = typeof data === 'object' ? data : {};
        let result = new EdgeTypeInfoOfEdgeInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["weight"] = this.weight;
        data["type"] = this.type;
        data["info"] = this.info ? this.info.toJSON() : <any>undefined;
        return data;
    }
}

export interface IEdgeTypeInfoOfEdgeInfo {
    weight: number;
    type?: string | undefined;
    info?: EdgeInfo | undefined;
}

export class EdgeInfo implements IEdgeInfo {
    durations?: string[] | undefined;

    constructor(data?: IEdgeInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["durations"])) {
                this.durations = [] as any;
                for (let item of _data["durations"])
                    this.durations!.push(item);
            }
        }
    }

    static fromJS(data: any): EdgeInfo {
        data = typeof data === 'object' ? data : {};
        let result = new EdgeInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.durations)) {
            data["durations"] = [];
            for (let item of this.durations)
                data["durations"].push(item);
        }
        return data;
    }
}

export interface IEdgeInfo {
    durations?: string[] | undefined;
}

export class ValueTupleOfDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfoAndGraphLayoutOptions implements IValueTupleOfDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfoAndGraphLayoutOptions {
    item1!: DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo;
    item2!: GraphLayoutOptions;

    constructor(data?: IValueTupleOfDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfoAndGraphLayoutOptions) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.item1 = new DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo();
            this.item2 = new GraphLayoutOptions();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.item1 = _data["item1"] ? DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo.fromJS(_data["item1"]) : new DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo();
            this.item2 = _data["item2"] ? GraphLayoutOptions.fromJS(_data["item2"]) : new GraphLayoutOptions();
        }
    }

    static fromJS(data: any): ValueTupleOfDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfoAndGraphLayoutOptions {
        data = typeof data === 'object' ? data : {};
        let result = new ValueTupleOfDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfoAndGraphLayoutOptions();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["item1"] = this.item1 ? this.item1.toJSON() : <any>undefined;
        data["item2"] = this.item2 ? this.item2.toJSON() : <any>undefined;
        return data;
    }
}

export interface IValueTupleOfDirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfoAndGraphLayoutOptions {
    item1: DirectedGraphOfNodeOfNodeInfoAndEdgeOfEdgeInfo;
    item2: GraphLayoutOptions;
}

export class GraphLayoutOptions implements IGraphLayoutOptions {
    mergeEdgesOfSameType!: boolean;
    fixUnforeseenEdges!: boolean;
    nodeSeparation!: number;
    rankSeparation!: number;
    edgeSeparation!: number;

    constructor(data?: IGraphLayoutOptions) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.mergeEdgesOfSameType = _data["mergeEdgesOfSameType"];
            this.fixUnforeseenEdges = _data["fixUnforeseenEdges"];
            this.nodeSeparation = _data["nodeSeparation"];
            this.rankSeparation = _data["rankSeparation"];
            this.edgeSeparation = _data["edgeSeparation"];
        }
    }

    static fromJS(data: any): GraphLayoutOptions {
        data = typeof data === 'object' ? data : {};
        let result = new GraphLayoutOptions();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["mergeEdgesOfSameType"] = this.mergeEdgesOfSameType;
        data["fixUnforeseenEdges"] = this.fixUnforeseenEdges;
        data["nodeSeparation"] = this.nodeSeparation;
        data["rankSeparation"] = this.rankSeparation;
        data["edgeSeparation"] = this.edgeSeparation;
        return data;
    }
}

export interface IGraphLayoutOptions {
    mergeEdgesOfSameType: boolean;
    fixUnforeseenEdges: boolean;
    nodeSeparation: number;
    rankSeparation: number;
    edgeSeparation: number;
}

export class OcDfgLayoutOptions implements IOcDfgLayoutOptions {
    ocDfgOptions!: OcDfgOptions;
    layoutOptions!: GraphLayoutOptions;

    constructor(data?: IOcDfgLayoutOptions) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.ocDfgOptions = new OcDfgOptions();
            this.layoutOptions = new GraphLayoutOptions();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ocDfgOptions = _data["ocDfgOptions"] ? OcDfgOptions.fromJS(_data["ocDfgOptions"]) : new OcDfgOptions();
            this.layoutOptions = _data["layoutOptions"] ? GraphLayoutOptions.fromJS(_data["layoutOptions"]) : new GraphLayoutOptions();
        }
    }

    static fromJS(data: any): OcDfgLayoutOptions {
        data = typeof data === 'object' ? data : {};
        let result = new OcDfgLayoutOptions();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ocDfgOptions"] = this.ocDfgOptions ? this.ocDfgOptions.toJSON() : <any>undefined;
        data["layoutOptions"] = this.layoutOptions ? this.layoutOptions.toJSON() : <any>undefined;
        return data;
    }
}

export interface IOcDfgLayoutOptions {
    ocDfgOptions: OcDfgOptions;
    layoutOptions: GraphLayoutOptions;
}

export class ListTreeOfString implements IListTreeOfString {

    constructor(data?: IListTreeOfString) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): ListTreeOfString {
        data = typeof data === 'object' ? data : {};
        let result = new ListTreeOfString();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IListTreeOfString {
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}